a=input('digite algo:')
print('o ripo primitivo é', type(a))
print('É uma letra: ',end='')
print(a.isalpha())
print('É um número: ',end='')
print(a.isnumeric())
print('É letra e numero: ',end='')
print(a.isalnum())
print('É um decimal: ',end='')
print(a.isdecimal())
print('É um espaça: ',end='')
print(a.isspace())
